stages:
  - lint-js
  - e2e-test
  - deploy

image: cypress/base:14

lint js:
  stage: lint-js
  cache:
    untracked: true
    policy: pull
  script:
    - npm i # eslint eslint-config-airbnb-base eslint-plugin-import
    - npm run lint
  only:
    - merge_requests

run e2e test:
  stage: e2e-test
  cache:
    untracked: true
    policy: pull
  script:
    - npm i # cypress
    - cd src && npx static-server -p 8081 & $(npm bin)/cypress run --config baseUrl=http://localhost:8081
  only:
    - merge_requests

pages:
  stage: deploy
  image: node:16
  script:
    - set
    - echo "Deploying public/ folder to GitLab Pages"
    - bash bin/build-gitlab.sh
    - ls public/
  artifacts:
    paths:
      - public
  only:
    - master
