name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build
      run: bash bin/build.sh
    
    - name: Test
      run: |
        echo "$(date)" > date-stamp.txt
