name: Deploy to GitHub pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2
      with:
        version:  16.x

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Clean install dependencies
      run: npm ci

    - name: Deploy
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages
        git status
        npm run build
        ls dist/
        git --work-tree dist add .
        git --work-tree dist commit -m 'Deploy'
        git push origin HEAD:gh-pages -f
        rm -r dist
        git checkout -f master
        git branch -D gh-pages
